base_model_path: './pretrained_weights/sd-image-variations-diffusers'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
mm_path: ''

denoising_unet_path: ./pretrained_weights/denoising_unet.pth
reference_unet_path: ./pretrained_weights/reference_unet.pth
obj_encoder_path: ./pretrained_weights/obj_encoder.pth
cam_encoder_path: ./pretrained_weights/cam_encoder.pth

use_lora: false
lora_rank: 64

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp32'

is_obj: true
is_cam: true
is_depth: false
is_adapted: false
fusion_type: 'max'
is_pad: true

W: 768
H: 512
circle_scale: 10

sample_n_frames: 16
sample_stride: 4
guidance_scale: 3.5
steps: 20
seed: 12580

save_dir: './tmp'

sample_n_trajs: -1
cam_only: false
obj_only: false